export const mappings: { [key: string]: string } = {
  // Frontend Libraries / Frameworks
  "react.js": "react",
  reactjs: "react",
  react: "react",
  "next.js": "nextjs",
  nextjs: "nextjs",
  next: "nextjs",
  "vue.js": "vue",
  vuejs: "vue",
  vue: "vue",
  "angular.js": "angular",
  angularjs: "angular",
  angular: "angular",
  "svelte.js": "svelte",
  svelte: "svelte",
  "solid.js": "solid",
  solid: "solid",

  // Backend
  nodejs: "nodejs",
  node: "nodejs",
  "node.js": "nodejs",
  express: "express",
  "express.js": "express",
  django: "django",
  flask: "flask",
  laravel: "laravel",
  "spring boot": "spring",
  spring: "spring",
  fastapi: "fast",
  fast: "fast",
  nestjs: "nest",
  nest: "nest",
  rails: "rails",
  "ruby on rails": "rails",

  // Programming Languages
  javascript: "javascript",
  js: "javascript",
  typescript: "typescript",
  ts: "typescript",
  python: "python",
  java: "java",
  c: "c",
  "c++": "cpp",
  cpp: "cpp",
  csharp: "csharp",
  "c#": "csharp",
  php: "php",
  ruby: "ruby",
  kotlin: "kotlin",
  swift: "swift",
  go: "go",
  rust: "rust",
  dart: "dart",

  // CSS Frameworks / Tools
  tailwindcss: "tailwind",
  tailwind: "tailwind",
  bootstrap: "bootstrap",
  sass: "sass",
  scss: "sass",
  less: "less",
  css: "css",
  postcss: "postcss",

  // Design Tools
  figma: "figma",
  xd: "adobexd",
  "adobe xd": "adobexd",
  sketch: "sketch",
  photoshop: "photoshop",
  illustrator: "illustrator",
  framer: "framer",

  // Databases
  mongodb: "mongodb",
  "mongo db": "mongodb",
  mysql: "mysql",
  postgresql: "postgresql",
  postgres: "postgresql",
  sqlite: "sqlite",
  mariadb: "mariadb",
  redis: "redis",
  firebase: "firebase",
  supabase: "supabase",

  // DevOps / Tools / Platforms
  docker: "docker",
  kubernetes: "kubernetes",
  git: "git",
  github: "github",
  gitlab: "gitlab",
  bitbucket: "bitbucket",
  netlify: "netlify",
  vercel: "vercel",
  aws: "aws",
  azure: "azure",
  gcp: "gcp",
  heroku: "heroku",
  nginx: "nginx",

  // Testing
  jest: "jest",
  mocha: "mocha",
  chai: "chai",
  cypress: "cypress",
  playwright: "playwright",
  selenium: "selenium",

  //Data-Science
  pandas: "pandas",
  numpy: "numpy",
  scikit: "sklearn",
  "scikit-learn": "sklearn",
  sklearn: "sklearn",
  tensorflow: "tensorflow",
  pytorch: "pytorch",
  keras: "keras",
  jupyter: "jupyter",
  "jupyter notebook": "jupyter",

  // Misc Tools
  webpack: "webpack",
  vite: "vite",
  babel: "babel",
  eslint: "eslint",
  prettier: "prettier",
  postman: "postman",
};
