export const voices = [
  {
    name: "Rohan",
    gender: "Male",
    accent: "Indian American",
    age: "24 years old",
    characteristics: ["bright", "optimistic", "cheerful", "energetic"],
    default: true,
    audio: "/audios/rohan.mp3",
  },
  {
    name: "Hana",
    gender: "Female",
    accent: "American",
    age: "22 years old",
    characteristics: ["soft", "soothing", "gentle"],
    default: false,
    audio: "/audios/hana.mp3",
  },
  {
    name: "Harry",
    gender: "Male",
    accent: "American",
    age: "24 years old",
    characteristics: ["clear", "energetic", "professional"],
    default: false,
    audio: "/audios/harry.mp3",
  },
  {
    name: "Elliot",
    gender: "Male",
    accent: "Canadian",
    age: "25 years old",
    characteristics: ["soothing", "friendly", "professional"],
    default: false,
    audio: "/audios/elliot.mp3",
  },
  {
    name: "Paige",
    gender: "Female",
    accent: "American",
    age: "26 years old",
    characteristics: ["deeper tone", "calming", "professional"],
    default: false,
    audio: "/audios/paige.mp3",
  },
  {
    name: "Cole",
    gender: "Male",
    accent: "American",
    age: "22 years old",
    characteristics: ["deeper tone", "calming", "professional"],
    default: false,
    audio: "/audios/cole.mp3",
  },
  {
    name: "Savannah",
    gender: "Female",
    accent: "American (Southern)",
    age: "25 years old",
    characteristics: ["Southern American Accent"],
    default: false,
    audio: "/audios/savannah.mp3",
  },
  {
    name: "Spencer",
    gender: "Female",
    accent: "American",
    age: "26 years old",
    characteristics: [
      "energetic",
      "quippy",
      "lighthearted",
      "cheeky",
      "amused",
    ],
    default: false,
    audio: "/audios/spencer.mp3",
  },
];
