"use client";

import { useState } from "react";
import { FaChevronDown, FaSearch } from "react-icons/fa";

interface FAQItem {
  question: string;
  answer: string;
  category: string;
}

const faqData: FAQItem[] = [
  {
    category: "Getting Started",
    question: "What is BolAi?",
    answer:
      "BolAi is an AI-powered interview preparation platform that helps you practice for technical and behavioral interviews. 'Bol' means 'speak' in Nepali, reflecting our mission to help you speak with confidence in interviews.",
  },
  {
    category: "Getting Started",
    question: "How do I start my first interview?",
    answer:
      "Navigate to the 'Generate Interview' page from the sidebar, select your desired role, experience level, and interview type. Click 'Generate Interview' and you'll be connected with our AI interviewer to start practicing.",
  },
  {
    category: "Getting Started",
    question: "Do I need any special equipment?",
    answer:
      "You'll need a microphone and speakers or headphones to conduct voice interviews. Make sure to allow microphone access when prompted by your browser.",
  },
  {
    category: "Interviews",
    question: "What types of interviews can I practice?",
    answer:
      "You can practice Technical interviews (coding, system design), Behavioral interviews (past experiences, situational questions), or Mixed interviews that combine both types.",
  },
  {
    category: "Interviews",
    question: "How long does an interview session last?",
    answer:
      "Interview sessions typically last 15-30 minutes depending on the number of questions and your response depth. You can end the session anytime.",
  },
  {
    category: "Interviews",
    question: "Can I pause or restart an interview?",
    answer:
      "You cannot pause an active interview, but you can end it anytime. You can generate a new interview session whenever you want to practice again.",
  },
  {
    category: "Feedback",
    question: "When will I receive feedback?",
    answer:
      "You'll receive detailed feedback immediately after completing your interview. The feedback includes your performance score, strengths, areas for improvement, and specific suggestions.",
  },
  {
    category: "Feedback",
    question: "What does the feedback include?",
    answer:
      "Feedback includes an overall score, analysis of your communication skills, technical accuracy (for technical interviews), clarity of responses, and personalized recommendations for improvement.",
  },
  {
    category: "Feedback",
    question: "Can I review my past interviews?",
    answer:
      "Yes! Go to 'My Feedbacks' in the sidebar to view all your past interview feedbacks and track your progress over time.",
  },
  {
    category: "Features",
    question: "What is the Interview Hub?",
    answer:
      "Interview Hub is a community feature where you can explore interviews generated by other users. You can practice with the same questions and compare your approach.",
  },
  {
    category: "Features",
    question: "Can I share my interviews with others?",
    answer:
      "Yes, interviews you generate are automatically added to the Interview Hub (anonymously) so others in the community can learn from them.",
  },
  {
    category: "Features",
    question: "How does the AI interviewer work?",
    answer:
      "Our AI interviewer uses advanced natural language processing to understand your responses, ask relevant follow-up questions, and provide realistic interview experiences tailored to your role and level.",
  },
  {
    category: "Account",
    question: "Is BolAi free to use?",
    answer:
      "Yes! BolAi offers a free plan with core features. We also offer premium plans with additional features like unlimited interviews and advanced feedback analytics.",
  },
  {
    category: "Account",
    question: "How do I upgrade my account?",
    answer:
      "Visit the 'Subscription' page from the sidebar to view our pricing plans and upgrade options. Choose a plan that fits your needs and follow the payment process.",
  },
  {
    category: "Account",
    question: "Is my data secure?",
    answer:
      "Absolutely! We take data security seriously. All your interview data is encrypted and stored securely. We never share your personal information with third parties.",
  },
  {
    category: "Technical",
    question: "Which browsers are supported?",
    answer:
      "BolAi works best on modern browsers including Chrome, Firefox, Safari, and Edge. Make sure your browser is updated to the latest version for the best experience.",
  },
  {
    category: "Technical",
    question: "Why isn't my microphone working?",
    answer:
      "Make sure you've granted microphone permissions to your browser. Check your browser settings and ensure no other application is using the microphone. Try refreshing the page if issues persist.",
  },
  {
    category: "Technical",
    question: "What if I experience technical issues during an interview?",
    answer:
      "If you face any technical issues, try refreshing the page or starting a new session. If problems continue, please contact our support team through the feedback form.",
  },
];

const FAQPage = () => {
  const [openIndex, setOpenIndex] = useState<number | null>(null);
  const [selectedCategory, setSelectedCategory] = useState<string>("All");
  const [searchQuery, setSearchQuery] = useState<string>("");

  const categories = [
    "All",
    ...Array.from(new Set(faqData.map((faq) => faq.category))),
  ];

  const filteredFAQs = faqData.filter((faq) => {
    const matchesCategory =
      selectedCategory === "All" || faq.category === selectedCategory;
    const matchesSearch =
      searchQuery === "" ||
      faq.question.toLowerCase().includes(searchQuery.toLowerCase()) ||
      faq.answer.toLowerCase().includes(searchQuery.toLowerCase());
    return matchesCategory && matchesSearch;
  });

  const toggleFAQ = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <div className="w-full min-h-screen flex flex-col justify-start items-center overflow-y-auto mt-4 px-5">
      {/* Banner Section */}
      <div className="w-[95%] md:w-[98%] lg:w-[90%] h-[45vh] md:h-[38vh] lg:h-[40vh] bg-gray-900/90 rounded-md flex flex-col justify-start items-start md:flex-row md:justify-between md:items-center lg:flex-row lg:justify-between lg:items-center mb-4">
        {/* Banner Content */}
        <div className="w-full lg:w-[55%] md:w-[58%] flex flex-col justify-center items-start lg:items-start md:items-start p-6 mt-2">
          {/* Title */}
          <div className="text-2xl md:text-3xl lg:text-3xl text-white font-semibold mb-4">
            Frequently Asked Questions
          </div>
          {/* SubText */}
          <div className="text-md md:text-xl lg:text-md text-white mb-6">
            Find answers to common questions about BolAi and how to make the
            most of your interview preparation journey.
          </div>
        </div>
        {/* Banner Image */}
        <div
          className="max-sm:hidden md:w-[40%] md:h-[32vh] lg:w-[34%] lg:h-[34vh]"
          style={{
            backgroundImage: `url(/faq.svg)`,
            backgroundPosition: "center center",
            backgroundSize: "contain",
            backgroundRepeat: "no-repeat",
          }}
        ></div>
      </div>

      {/* Search Bar */}
      <div className="w-[95.5%] md:w-[95%] lg:w-[90%] max-w-4xl">
        <div className="relative">
          <FaSearch className="absolute left-4 top-1/2 transform -translate-y-1/2 text-gray-400" />
          <input
            type="text"
            placeholder="Search FAQs..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full pl-12 pr-4 py-3 bg-gray-800/50 border border-gray-700/50 rounded-lg text-white placeholder-gray-400 focus:outline-none focus:border-green-500/50 focus:ring-2 focus:ring-green-500/20 transition-all duration-200"
          />
        </div>
      </div>

      {/* Category Filter */}
      <div className="w-[95.5%] md:w-[95%] lg:w-[90%] max-w-5xl">
        `
        <div className="flex flex-wrap gap-3 justify-center mb-8">
          {categories.map((category) => (
            <button
              key={category}
              onClick={() => setSelectedCategory(category)}
              className={`px-4 py-2 rounded-lg font-medium transition-all duration-200 ${
                selectedCategory === category
                  ? "bg-green-600 text-white shadow-lg"
                  : "bg-gray-800 text-gray-300 hover:bg-gray-700 border border-gray-700"
              }`}
            >
              {category}
            </button>
          ))}
        </div>
      </div>

      {/* FAQ List */}
      <div className="w-[95.5%] md:w-[95%] lg:w-[90%] max-w-4xl mb-8">
        {filteredFAQs.length === 0 ? (
          <div className="text-center py-12">
            <p className="text-gray-400 text-lg">
              No FAQs found matching your search.
            </p>
            <p className="text-gray-500 text-sm mt-2">
              Try adjusting your search or category filter.
            </p>
          </div>
        ) : (
          <div className="space-y-4">
            {filteredFAQs.map((faq, index) => (
              <div
                key={index}
                className="bg-gray-800/50 border border-gray-700/50 rounded-lg overflow-hidden transition-all duration-300 hover:border-gray-600"
              >
                <button
                  onClick={() => toggleFAQ(index)}
                  className="w-full flex justify-between items-center p-5 text-left hover:bg-gray-700/30 transition-colors duration-200"
                >
                  <div className="flex-1 pr-4">
                    <span className="text-xs text-green-400 font-medium mb-1 block">
                      {faq.category}
                    </span>
                    <h3 className="text-base md:text-lg font-semibold text-white">
                      {faq.question}
                    </h3>
                  </div>
                  <FaChevronDown
                    className={`text-gray-400 transition-transform duration-300 flex-shrink-0 ${
                      openIndex === index ? "rotate-180" : ""
                    }`}
                  />
                </button>
                <div
                  className={`overflow-hidden transition-all duration-300 ${
                    openIndex === index ? "max-h-96" : "max-h-0"
                  }`}
                >
                  <div className="p-5 pt-0 text-gray-300 leading-relaxed">
                    {faq.answer}
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Contact Section */}
      <div className="w-[95.5%] md:w-[95%] lg:w-[90%] max-w-4xl mb-8">
        <div className="bg-gradient-to-r from-green-600/20 to-emerald-600/20 border border-green-500/30 rounded-lg p-6 text-center">
          <h3 className="text-xl md:text-2xl font-bold text-white mb-3">
            Still have questions?
          </h3>
          <p className="text-gray-300 mb-4">
            Can&apos;t find the answer you&apos;re looking for? Feel free to
            reach out to our support team.
          </p>
          <button className="px-6 py-3 bg-green-600 hover:bg-green-700 text-white font-medium rounded-lg transition-all duration-200 hover:scale-105">
            Contact Support
          </button>
        </div>
      </div>
    </div>
  );
};

export default FAQPage;
